KR:
  settlement: 07079 # Burgas. See: https://www.nsi.bg/nrnm/ekatte/index OR https://www.ekatte.com
  name: "Анет4 Меден Рудник А"
  address: "гр. Бургас ул. ХХХ №Х"
  path_to_db: ./items.DB

MRA:
  settlement: 07079
  name: "Анет4 Меден Рудник А"
  address: "гр. Бургас ул. ХХХ №Х"
  path_to_db: ./items.DB

MRB:
  settlement: 07079
  name: "Анет4 Меден Рудник А"
  address: "гр. Бургас ул. ХХХ №Х"
  path_to_db: ./items.DB

MRV:
  settlement: 07079
  name: "Анет4 Меден Рудник А"
  address: "гр. Бургас ул. ХХХ №Х"
  path_to_db: ./items.DB

MRZ:
  settlement: 07079
  name: "Анет4 Меден Рудник А"
  address: "гр. Бургас ул. ХХХ №Х"
  path_to_db: ./items.DB

TR:
  settlement: 07079
  name: "Анет4 Меден Рудник А"
  address: "гр. Бургас ул. ХХХ №Х"
  path_to_db: ./items.DB
