processing:
  mode: startup # Options: startup, manual, scheduled
  scheduled_time: "03:00"  # Only used if mode is scheduled (format: "HH:MM")

markets:
  - settlement: 07079
    name: "Анет4 KR"
    address: "гр. Бургас ул. ХХХ №Х"
    path_to_db: ./items.DB
  - settlement: 07079
    name: "Анет4 Меден Рудник А"
    address: "гр. Бургас ул. ХХХ №Х"
    path_to_db: ./items.DB
  - settlement: 07079
    name: "Анет4 Меден Рудник B"
    address: "гр. Бургас ул. ХХХ №Х"
    path_to_db: ./items.DB
  - settlement: 07079
    name: "Анет4 Меден Рудник V"
    address: "гр. Бургас ул. ХХХ №Х"
    path_to_db: ./items.DB
  - settlement: 07079
    name: "Анет4 Меден Рудник Z"
    address: "гр. Бургас ул. ХХХ №Х"
    path_to_db: ./items.DB
  - settlement: 07079
    name: "Анет4 Меден Рудник TR"
    address: "гр. Бургас ул. ХХХ №Х"
    path_to_db: ./items.DB
