# Generated by pip2nix 0.8.0.dev1
# Used command: nix --extra-experimental-features "nix-command flakes" run github:nix-community/pip2nix -- generate pypxlib
# See https://github.com/nix-community/pip2nix

{ pkgs, fetchurl, fetchgit, fetchhg }:

self: super: {
  "pypxlib" = super.buildPythonPackage rec {
    pname = "pypxlib";
    version = "2.5";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/7e/03/c211668d1b39b45ed25d4ea0542fb0da18a16e58b1ec921b379f8b4e752e/pypxlib-2.5.tar.gz";
      sha256 = "0nilywxv8jhlg4vjw3jxxk5081y8s1lsj2nkjyi3mgs0wcxqr1i8";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
}
