# Generated by pip2nix 0.8.0.dev1
# See https://github.com/nix-community/pip2nix

{ pkgs, fetchurl, fetchgit, fetchhg }:

self: super: {
  "flaskwebgui" = super.buildPythonPackage rec {
    pname = "flaskwebgui";
    version = "1.1.6";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/f0/97/aecd915b2a4ce78a787a8f21f71483b1197cfcc1fb3b48f53378b0d38c00/flaskwebgui-1.1.6-py3-none-any.whl";
      sha256 = "0q9n7g2qd03rih7kacr4br98yyvl02vvd70bab2p87h00s9w2w5z";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."psutil"
    ];
  };
  "psutil" = super.buildPythonPackage rec {
    pname = "psutil";
    version = "6.1.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/1f/5a/07871137bb752428aa4b659f910b399ba6f291156bdea939be3e96cae7cb/psutil-6.1.1.tar.gz";
      sha256 = "1xg2a0ml4js61krvfihpf48ndwsjpsaniw4qa6sd1whqiir9d16g";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "pypxlib" = super.buildPythonPackage rec {
    pname = "pypxlib";
    version = "2.5";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/7e/03/c211668d1b39b45ed25d4ea0542fb0da18a16e58b1ec921b379f8b4e752e/pypxlib-2.5.tar.gz";
      sha256 = "0nilywxv8jhlg4vjw3jxxk5081y8s1lsj2nkjyi3mgs0wcxqr1i8";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
}
